name: Build and Run Docker Container

on: push  # Runs on every push

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Test Engine
        uses: shivamkonkar/ExecDockerGithubActions@V2
        with:
          storage_id: ${{ secrets.STORAGE_ID }}
