name: Build and Run Docker Container

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Print Repository Variable
        run: echo "The value of TEST_VARIABLE is ${{ vars.TEST_VARIABLE }}"

      - name: Run Test Engine
        uses: shivamkonkar/ExecDockerGithubActions@v4
        with:
          storage_id: ${{ vars.TEST_VARIABLE }}
