name: Build and Run Docker Container

on: push

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build --build-arg STORAGE_ID=${{ secrets.STORAGE_ID }} -t shivamkonkar/demo-test-engine .

      - name: Run Test Engine
        uses: shivamkonkar/ExecDockerGithubActions@v3
        with:
          storage_id: ${{ secrets.STORAGE_ID }}


jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Test Engine
        uses: shivamkonkar/ExecDockerGithubActions@v0
        with:
          storage_id: ${{ secrets.STORAGE_ID }}
